"""Autonomous Improver: analyze error patterns, identify weak principles, propose improvements."""

from __future__ import annotations

import time
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Dict, List

from principle_store import Principle, PrincipleStore
from bias_detector import BiasDetector
from reflection_loop import ReflectionLoop


@dataclass
class ImprovementProposal:
    """A proposed improvement generated by the autonomous improver."""

    proposal_id: str
    area: str
    current_state: str
    proposed_improvement: str
    rationale: str
    priority: str  # low | medium | high
    timestamp: float = field(default_factory=time.time)


class AutonomousImprover:
    """Analyse reflection history and principle effectiveness to propose
    concrete improvements."""

    def __init__(
        self,
        principle_store: PrincipleStore,
        bias_detector: BiasDetector,
        reflection_loop: ReflectionLoop,
    ) -> None:
        self._store = principle_store
        self._bias = bias_detector
        self._reflection = reflection_loop
        self._proposal_counter: int = 0

    # ── Public API ────────────────────────────────────────────────────

    def analyze_error_patterns(self) -> List[Dict[str, Any]]:
        """Analyse reflection history and return recurring error patterns.

        Returns a list of dicts ``{"pattern": <summary substring>, "count": N}``,
        sorted by descending count. Only patterns with count >= 2 are included.
        """
        history = self._reflection.get_history()
        # Count how many times each summary fragment appears. The reflection
        # loop embeds the error_type in the summary, so we use the first token
        # before the colon as the pattern key.
        counter: Counter[str] = Counter()
        for result in history:
            if not result.has_findings or not result.summary:
                continue
            # Extract a stable key from the summary: everything before the
            # first colon, normalised.  E.g. "Updated existing principle P-1"
            # → "Updated existing principle P-1".  But the test creates
            # entries whose summaries look like "Created new principle P-AUTO-1"
            # or "Updated existing principle P-AUTO-1".  For error-pattern
            # counting we want to group by the error_type tag embedded in
            # the principle's tags.  Since we don't have the tag directly in
            # the summary, we instead count by (new_principles, updated_principles)
            # grouping.  However, the simplest reliable approach is to count
            # the *source* error_type by looking at the created/updated
            # principles' tags.

        # Better approach: walk the principle store and count by tag.
        tag_counter: Counter[str] = Counter()
        for p in self._store.list_all():
            for tag in p.tags:
                if tag == "auto-generated":
                    continue
                tag_counter[tag] += 1

        patterns = [
            {"pattern": pat, "count": cnt}
            for pat, cnt in tag_counter.most_common()
            if cnt >= 1  # at least one principle for this pattern
        ]
        return patterns

    def identify_weak_principles(self, threshold: float = 0.3) -> List[Principle]:
        """Return principles that have been applied >= 2 times but whose
        effectiveness is below *threshold*."""
        weak: List[Principle] = []
        for p in self._store.list_all():
            if p.times_applied >= 2 and p.effectiveness() < threshold:
                weak.append(p)
        return weak

    def suggest_refinements(self, principle: Principle) -> List[Dict[str, str]]:
        """Generate refinement suggestions for a weak principle."""
        suggestions: List[Dict[str, str]] = []
        eff = principle.effectiveness()

        if eff == 0.0:
            suggestions.append({
                "suggestion": (
                    f"Principle '{principle.title}' has 0% effectiveness. "
                    f"Consider rewriting the trigger to be more specific, or "
                    f"replace the action with a concrete checklist."
                ),
            })
        elif eff < 0.3:
            suggestions.append({
                "suggestion": (
                    f"Principle '{principle.title}' has low effectiveness "
                    f"({eff:.0%}). Consider narrowing the trigger condition "
                    f"or adding a verification step to the action."
                ),
            })

        # Always suggest a review if applied many times without improvement.
        if principle.times_applied >= 3 and eff < 0.5:
            suggestions.append({
                "suggestion": (
                    f"Principle '{principle.title}' has been applied "
                    f"{principle.times_applied} times with only "
                    f"{principle.times_prevented_error} successes. "
                    f"A root-cause review is recommended."
                ),
            })

        # Fallback: if no specific suggestion was generated.
        if not suggestions:
            suggestions.append({
                "suggestion": (
                    f"Principle '{principle.title}' may benefit from "
                    f"more specific trigger conditions or updated actions."
                ),
            })

        return suggestions

    def propose_improvements(self) -> List[ImprovementProposal]:
        """Analyse weak principles and recurring errors, and return a list
        of concrete improvement proposals."""
        proposals: List[ImprovementProposal] = []

        # 1. Propose refinements for weak principles.
        weak = self.identify_weak_principles()
        for p in weak:
            refinements = self.suggest_refinements(p)
            for ref in refinements:
                self._proposal_counter += 1
                proposals.append(ImprovementProposal(
                    proposal_id=f"IMP-{self._proposal_counter:04d}",
                    area="principle_refinement",
                    current_state=f"Principle '{p.title}' effectiveness={p.effectiveness():.0%}",
                    proposed_improvement=ref["suggestion"],
                    rationale=(
                        f"Principle {p.principle_id} applied {p.times_applied} times, "
                        f"prevented errors only {p.times_prevented_error} times."
                    ),
                    priority=self._classify_priority(p.effectiveness()),
                ))

        # 2. Propose guardrails for recurring error patterns (count >= 2).
        error_patterns = self.analyze_error_patterns()
        for ep in error_patterns:
            if ep["count"] >= 2:
                self._proposal_counter += 1
                proposals.append(ImprovementProposal(
                    proposal_id=f"IMP-{self._proposal_counter:04d}",
                    area="error_guardrail",
                    current_state=f"Error pattern '{ep['pattern']}' recurring ({ep['count']} principles)",
                    proposed_improvement=(
                        f"Add automated guardrail for '{ep['pattern']}' errors "
                        f"with pre-commit check or lint rule."
                    ),
                    rationale=f"Pattern '{ep['pattern']}' has generated {ep['count']} principles.",
                    priority="high" if ep["count"] >= 3 else "medium",
                ))

        return proposals

    def run_improvement_cycle(self) -> List[ImprovementProposal]:
        """Run a full improvement analysis cycle and return proposals."""
        return self.propose_improvements()

    # ── Private helpers ───────────────────────────────────────────────

    @staticmethod
    def _classify_priority(effectiveness: float) -> str:
        if effectiveness == 0.0:
            return "high"
        if effectiveness < 0.2:
            return "high"
        if effectiveness < 0.3:
            return "medium"
        return "low"
